### PR TITLE
SENG-63 added video to theme SDK

### PR DESCRIPTION
**Pull request by JackHowa**
Cherrypicked from #94 

@chenghsinw , can you fill out checklist? 

## Description
Added Video component to SDK

## Jira Ticket
https://arcpublishing.atlassian.net/browse/SENG-63

## Acceptance Criteria
support autoplay, playthrough, and play in place

## Test Steps
- check the storybook examples

### Before
Doesn't exist

### After
New Video component
screencast 2020-09-21 16-16-19

## Dependencies or Side Effects
The playerRoot and videoOrg Fusion environment variables must be defined in order to load the POWA player's library.

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps above are working
- [x] Confirmed there are no linter errors
- [x] Confirmed this PR has reasonable code coverage
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by JackHowa** [comment]
Great work with storybook. Looks like there's an accessibility violation on the form label in storybook. Looks like it could be a quick fix

Screen Shot 2020-09-24 at 9 10 32 AM

**Comment by JackHowa** [comment]
There's linting errors related to the video branch. Can you fix them @chenghsinw? 

```
it-20750:engine-theme-sdk howardj$ npm run lint

> @wpmedia/engine-theme-sdk@2.2.6-canary.1 lint /Users/howardj/sites/engine-theme-sdk
> eslint . --ext .ts,.js,.tsx,.jsx


/Users/howardj/sites/engine-theme-sdk/src/components/Video/index.test.jsx
   7:32  error  Missing semicolon                              semi
   8:5   error  Missing semicolon                              semi
  22:43  error  Missing semicolon                              semi
  38:43  error  Missing semicolon                              semi
  54:43  error  Missing semicolon                              semi
  70:43  error  Missing semicolon                              semi
  73:4   error  Newline required at end of file but not found  eol-last

/Users/howardj/sites/engine-theme-sdk/src/components/Video/index.tsx
   5:33  warning  Unexpected any. Specify a different type                                                                           @typescript-eslint/no-explicit-any
  47:41  error    The closing bracket must be aligned with the line containing the opening tag (expected column 7 on the next line)  react/jsx-closing-bracket-location

✖ 9 problems (8 errors, 1 warning)
  8 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @wpmedia/engine-theme-sdk@2.2.6-canary.1 lint: `eslint . --ext .ts,.js,.tsx,.jsx`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @wpmedia/engine-theme-sdk@2.2.6-canary.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/howardj/.npm/_logs/2020-09-24T15_58_11_902Z-debug.log
it-20750:engine-theme-sdk howardj$

**Comment by JackHowa** [comment]
looks good -- thanks. I can merge and deploy. looks like bc I made pr, I can't approve but I do

**Comment by JackHowa** [comment]
@chenghsinw published to canary tag `canary: 2.3.0-canary.0`. In order to use canary tag for engine-theme-sdk, make sure you're on fusion `2.6.3-blockrelease.1`

**Comment by chenghsinw** [comment]
@JackHowa what does `2.6.3-blockrelease.1` mean? Where should I put it

**Comment by JackHowa** [comment]
if you're doing local block themes development, you can specify it in the .env file https://github.com/WPMedia/fusion-news-theme-blocks/blob/stable/News%20Theme%20Development.md#npm-link-local-development-instructions

**Comment by JackHowa** [comment]
in Fusion-News-Theme repo, 

.env
```
FUSION_RELEASE=2.6.3-blockrelease.1
ENGINE_SDK_DIST_TAG=canary
BLOCK_DIST_TAG=canary
```

**Comment by chenghsinw** [comment]
Cool, thank u

**Pull request merged**
