### PR TITLE
TMEDIA-677 Vertically center gallery 

### PR DESCRIPTION
**Pull request by JackHowa**
## Description
Vertically center gallery images

## Jira Ticket
- [TMEDIA-677](https://arcpublishing.atlassian.net/browse/TMEDIA-677)

## Acceptance Criteria
On safari, the image should be vertically centered in the gallery

On safari, the ad in the gallery should be vertically centered in the gallery and no part of the image should be shown

### Storybook

1. Open safari 
2. Open the chromatic page for this 
3. Go to the gallery
4. Open the new tab so it's full-screen 
Screen Shot 2022-02-09 at 15 24 49

5. Scroll around and see evenly-distributed black area above and below the images
6. Go to a story with an ad 

7. Scroll to the ad. You should not see the image underneath the ad. (It's actually no longer rendered now, rather than hidden below. In my mind, this is an improvement.) 
Screen Shot 2022-02-09 at 15 31 32

### Live 

1. Link engine theme sdk locally `npx fusion start -f -l @wpmedia/engine-theme-sdk`
2. Open safari http://localhost/pf/gallery-ad-test/?_website=the-sun
3. See the ads render on sliding through the gallery
4. Ensure images are vertically centered

Screen Shot 2022-02-09 at 17 24 50

### Before

Screen Shot 2022-02-09 at 14 45 27

### After
Screen Shot 2022-02-09 at 14 45 04

## Dependencies or Side Effects
- When there's an ad above an image, the interaction of the ad moving over the image has changed. I'm not sure if this was the desired behavior from before

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x] Confirmed all the test steps above are working
- [x] Confirmed there are no linter errors
- [ ] Confirmed this PR has reasonable code coverage
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by JackHowa** [comment]
outage with chromatic https://twitter.com/chromaui/status/1491538505775955971

**Comment by JackHowa** [comment]
Figuring out the best way to do this -- moving to draft

**Review by nschubach — APPROVED** [review]
Looks good!

**Comment by brentmiller1973** [comment]
@JackHowa Seeing a couple images not centered (Safari):

image

image

**Comment by brentmiller1973** [comment]
@JackHowa Perhaps a `margin:auto` on the `picture` element will fix what I'm seeing above

image

**Comment by brentmiller1973** [comment]
@JackHowa So the above is not an issue then?

**Pull request merged**
