### PR TITLE
ci: Update sb via `npx sb upgrade --use-npm` working as expected

### PR DESCRIPTION
**Pull request by JackHowa**
- upgrade storybook per warnings and dependabot

### CODE REVIEW

**Comment by matthewroach** [comment]
Can we fix the warnings in console?

Code-2021-05-17-17-43 19

**Comment by JackHowa** [comment]
> Can we fix the warnings in console?
> 
> Code-2021-05-17-17-43 19

yeah will look into, will look at your fix for this in blocks

**Comment by JackHowa** [comment]
updated: 

```
npm run storybook

> @wpmedia/engine-theme-sdk@2.9.6-canary.16 storybook /Users/howardj/sites/engine-theme-sdk
> start-storybook -p 6006

info @storybook/react v6.2.9
info 
info => Loading presets
info => Loading custom babel config
info => Loading 1 config file in "/Users/howardj/sites/engine-theme-sdk/.storybook"
info => Loading 9 other files in "/Users/howardj/sites/engine-theme-sdk/.storybook"
info => Loading custom manager config
info => Loading custom babel config
info => Adding stories defined in "/Users/howardj/sites/engine-theme-sdk/.storybook/main.js"
info => Using implicit CSS loaders
info => Loading custom manager config
info => Using default Webpack4 setup
(node:23696) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
10% building 3/4 modules 1 active .../webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefinedinfo => Using cached manager
webpack built preview 7fb02fd965bfd8a3e436 in 16495ms
╭───────────────────────────────────────────────────╮

**Comment by JackHowa** [comment]
tried a couple things, but odd that changing the root babel config affected and fixed this. shouldn't need to do that. seems like it's a bug in sb https://github.com/storybookjs/storybook/issues/14805

**Comment by matthewroach** [comment]
Did you mean to close this? Getting onto v6 would be nice

**Comment by JackHowa** [comment]
@matthewroach yeah I did mean to close it. looked like 6.2.9 was having some issues with babel 

we're on v6 already

**Comment by JackHowa** [comment]
I was able to quiet them by changing the root babel config. but that seemed like it was not working as expected if I couldn't change the babelrc in the storybook folder or main.js plugins to quiet the warning  https://github.com/WPMedia/engine-theme-sdk/pull/345/commits/3f16c0273d93465498f9516cba4a0cb2d561c738

**Pull request closed without merging**
