### PR TITLE
THEMES-1073: Removing date utilities

### PR DESCRIPTION
**Pull request by vgalatro**
## Description

This PR removes the localizeDate and localizeDateTime utilities, as they've been moved to `arc-themes-components`.

## Jira Ticket

- [THEMES-1073](https://arcpublishing.atlassian.net/browse/THEMES-1073)

## Acceptance Criteria

- updating import references
- move mocks from tests (if exist)

## Test Steps

- See `arc-themes-blocks` PR: https://github.com/WPMedia/arc-themes-blocks/pull/1651

## Dependencies or Side Effects

- `arc-themes-blocks`: https://github.com/WPMedia/arc-themes-blocks/pull/1651

## Review Checklist

- [x] Confirmed all the test steps above are working
- [x] Confirmed there are no linter errors
- [x] Confirmed this PR has reasonable code coverage
  - [x] Confirmed this PR has unit test files
  - [x] Ran `npm test`, made sure all tests are passing
  - [x] If the amount of work to write unit tests for this change are excessive,
        please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

[THEMES-1073]: https://arcpublishing.atlassian.net/browse/THEMES-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by nschubach — COMMENTED** [review]
debugging-timezone-postinstall-dates.md ?

**Comment by vgalatro** [comment]
Looking at that lead me to `scripts/postinstall.js`. Do you think that should be in `arc-themes-components` as well?

**Comment by nschubach** [comment]
I'm thinking it might have to be... looks like it's important to keeping the tz data up to date

Could potentially take queue from the postinstall in here @annasherman for the stylebuilder ticket?

**Comment by vgalatro** [comment]
After going through it all, it's definitely for managing the bundle size. The timezone package is 3.4MB without the script, and only 172KB after it runs.

**Comment by vgalatro** [comment]
@nschubach , this is ready for review again, and there's a follow up PR for `arc-themes-components` to add in the postinstall script. Once that's merged in I'll make another blocks PR updating the lockfile.

**Review by nschubach — APPROVED** [review]
I think the deletion of the util SHOULD trigger the publish so let's see where this goes.  The removal looks complete to me.

**Pull request merged**
