### PR TITLE
feat: Add basic videoplayer component taking in video embed

### PR DESCRIPTION
**Pull request by JackHowa**
- see test instructions https://github.com/WPMedia/fusion-news-theme-blocks/pull/689

### CODE REVIEW

**Comment by JackHowa** [comment]
- [ ] improve test coverage 
--------------------------------|----------|----------|----------|----------|-------------------|
Jest: "global" coverage threshold for branches (68%) not met: 67.47%

Test Suites: 86 passed, 86 total
Tests:       1044 passed, 1044 total
Snapshots:   0 total
Time:        23.826s
Ran all test suites.
npm ERR! code ELIFECYCLE

```

can add the following from the blocks for testing playthorugh manipulation: 

```

  // it('if autplay is enabled, add autoplay props ', () => {
  //   const testEmbed = '<div class="powa" id="powa-e924" data-org="corecomponents" data-env="prod"'
  //   + ' data-uuid="e924e51b" data-aspect-ratio="0.562" data-api="prod"><script '
  //   + 'src="//d2w3jw6424abwq.cloudfront.net/prod/powaBoot.js?org=corecomponents"></script></div>';

  //   useFusionContext.mockImplementation(() => (
  //     { id: '12345' }));

  //   const getElementMock = jest.fn();
  //   getElementMock.mockReturnValue({ firstElementChild: {} });
  //   document.getElementById = getElementMock;

  //   getThemeStyle.mockImplementation(() => (
  //     { 'primary-font-family': 'Leopard' }));

  //   getProperties.mockImplementation(() => (
  //     'sampleSite'));

  //   const customFields = { inheritGlobalContent: false };
  //   const wrapper = mount(<VideoPlayer
  //     customFields={customFields}
  //     embedMarkup={testEmbed}
  //     enableAutoplay
  //   />);

  // parsing handled by engine theme sdk now
  // const expectedEmbed = {
  //   __html: '<div class="powa"  data-autoplay=true data-muted=true'
  //   + ' id="powa-e924" data-org="corecomponents" data-env="prod" data-uuid="e924e51b" '
  //   + 'data-aspect-ratio="0.562" data-api="prod"></div>',
  // };
  //   expect(wrapper.find('#video-12345').prop('dangerouslySetInnerHTML')).toEqual(expectedEmbed);
  // });

  // it('if playthrough is enabled, add playthrough props ', () => {
  //   const testEmbed = '<div class="powa" id="powa-e924" data-org="corecomponents" data-env="prod"'
  //   + ' data-uuid="e924e51b" data-aspect-ratio="0.562" data-api="prod"><script '
  //   + 'src="//d2w3jw6424abwq.cloudfront.net/prod/powaBoot.js?org=corecomponents"></script></div>';

  //   useFusionContext.mockImplementation(() => (
  //     { id: '12345' }));

  //   const getElementMock = jest.fn();
  //   getElementMock.mockReturnValue({ firstElementChild: {} });
  //   document.getElementById = getElementMock;

  //   const customFields = { inheritGlobalContent: false, playthrough: true };
  //   const wrapper = mount(<VideoPlayer
  //     customFields={customFields}
  //     embedMarkup={testEmbed}
  //     enableAutoplay
  //   />);

  //   const expectedEmbed = {
  //     __html: '<div class="powa"  data-autoplay=true data-muted=true  data-playthrough=true'
  //     + ' id="powa-e924" data-org="corecomponents" data-env="prod" data-uuid="e924e51b" '
  //     + 'data-aspect-ratio="0.562" data-api="prod"></div>',
  //   };
  //   expect(wrapper.find('#video-12345').prop('dangerouslySetInnerHTML')).toEqual(expectedEmbed);
  // });


handle this testing in the typescript

**Comment by JackHowa** [comment]
live on rc tag

**Comment by JackHowa** [comment]
todo: 

- [ ] Improve test coverage
- [ ] Ensure that typescript interface defaults are accurate 
- [ ] Possibly figure out whether we need to support enableAutoplay as well as autoplay
- [ ] Make sure this is pixel perfect without regressions 
- [ ] Implement the container potentially around this block per the video player
- [ ] add the alert, title and description to the block (although that is only used by the video-player-block itself at the moment) 
- [ ] Make sure the engine-theme-sdk video player can handle null or bad videos
- [ ] Document engine-theme-sdk video player with storybook and sample output

**Review by beltrancaliz — APPROVED** [review]
Tested on storybook locally and looks great, Good job!

**Comment by JackHowa** [comment]
huh weird tests didn't fail in github action ... will reinstall node modules and check

**Pull request merged**
