### PR TITLE
Update icons to be resizeable (wip)

### PR DESCRIPTION
**Pull request by kascote**
- updated all the icons to handle viewBox and size. 
- updated the Storybook to show the icons on different sizes, to be able to detect which ones do not support resizing out of the box.

localhost_6006_iframe html_id=icon--all-icons viewMode=story

### CODE REVIEW

**Comment by JackHowa** [comment]
Talk to me or @brandonhunty about this @kascote. I believe you should not need to use the style property to set height and width. you can use the width and height property as far as I can see

**Comment by kascote** [comment]
This PR try to address this issues:

on the current code, the icons are forced in css, some examples:

### story book
https://github.com/WPMedia/engine-theme-sdk/blob/316425021c81ec85113ce0317e98a5b5b5957f2d/src/components/icons/Icon.tsx#L25-L28

### sdk's Gallery component

expand button
https://github.com/WPMedia/engine-theme-sdk/blob/master/src/components/Gallery/styled.ts#L48-L50

next/prev button
https://github.com/WPMedia/engine-theme-sdk/blob/master/src/components/Gallery/styled.ts#L79-L80

is not using the Icon width and height params, and relaying on the previous css classes
https://github.com/WPMedia/engine-theme-sdk/blob/master/src/components/Gallery/index.tsx#L258


I tryed different approaches and some Brandon suggestions about the icon resize for the camera on PR #87 and no one worked. seems there was some issue on the svg. 
That was what I'm trying to see/fix on this PR, which other icons have the same issue, and after remove the custom css class and use different sizes, very few are able to resize.

**Comment by JackHowa** [comment]
Again, please look at https://staging.arcpublishing.com/alc/docs/storybooks/engine-theme-sdk/?path=/story/icon--custom-height-and-width at its docs tab for how to resize icons

**Comment by JackHowa** [comment]
Can resize with custom width and height prop

**Pull request closed without merging**
