### PR TITLE
SENG-63 added video to theme SDK

### PR DESCRIPTION
**Pull request by chenghsinw**
## Description
Added Video component to SDK

## Jira Ticket
https://arcpublishing.atlassian.net/browse/SENG-63

## Acceptance Criteria
support autoplay, playthrough, and play in place

## Test Steps
- check the storybook examples

### Before
Doesn't exist

### After
New Video component
screencast 2020-09-21 16-16-19

## Dependencies or Side Effects
The playerRoot and videoOrg Fusion environment variables must be defined in order to load the POWA player's library.

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps above are working
- [ ] Confirmed there are no linter errors
- [ ] Confirmed this PR has reasonable code coverage
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by chenghsinw** [comment]
The diff looks very weird since @JackHowa force-pushed changes to canary. Not sure what were the changes from the force-push

**Comment by chenghsinw** [comment]
The actually change is https://github.com/WPMedia/engine-theme-sdk/pull/94/commits/9d3be2f901907670671c3a472d7173b85c074540. If the force-push really changed the history, I might need to create another PR. Please let me know the context.

**Comment by JackHowa** [comment]
It shouldn't have had a major impact. can you rebase on top of canary or I can

**Comment by JackHowa** [comment]
thank you for using Storybook!

**Comment by JackHowa** [comment]
created a new pr -- thanks #95

**Pull request closed without merging**
