### PR TITLE
PEN-1539 avoid lightbox collapsed suddenly

### PR DESCRIPTION
**Pull request by amyerz**
## Description
- update to avoid lightbox collapse

## Jira Ticket
- [PEN-1539](https://arcpublishing.atlassian.net/browse/PEN-1539)

## Acceptance Criteria
- User should be able to navigate through the full gallery and go in and out of fullscreen mode.

## Test Steps
- in `Fusion-news-theme`, link to your local `engine-theme-sdk` repo in `.env` file  ENGINE_SDK_REPO={YOUR_LOCAL_PATH}/blocks/engine-theme-sdk
- run `npx fusion start -f -l` in ` Fusion-News-Theme` repo
- visit `http://localhost/news/2020/10/20/gallery-promo-item-with-festive-dishes-gallery/?_website=the-sun` 
- click on the expand button and click through the gallery with arrow buttons.
- the gallery should not collapsed suddenly

### Before
https://corecomponents.arcpublishing.com/pf/news/2020/10/20/gallery-promo-item-with-festive-dishes-gallery/?_website=washpost
Screen Shot 2020-11-28 at 10 35 07 AM

- while click through the gallery in lightbox (expanded), the lightbox crashed and the gallery missing on the page
Screen Shot 2020-11-28 at 10 34 37 AM

### After
- the lightbox should not be collapsed while image is missing
- may return "Image failed to load, but the gallery should not collapsed
Screen Shot 2020-11-28 at 10 57 32 AM

## Dependencies or Side Effects
_Examples of dependencies or side effects are:_
- Additional settings that will be required in the blocks.json
- Changes to the custom fields which will require users to reconfigure features
- Update to css framework or SDK
- Dependency on another PR that needs to be merged first

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [ ] Confirmed all the test steps above are working
- [ ] Confirmed there are no linter errors
- [ ] Confirmed this PR has reasonable code coverage
  - [ ] Confirmed this PR has unit test files
  - [ ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ ] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Review by beltrancaliz — CHANGES_REQUESTED** [review]
LGTM! Could we add a test case for this?

**Comment by amyerz** [comment]
> LGTM! Could we add a test case for this?

While I ran the tests, I am unable to load any images to the lightbox. The existing test do not have any images, and skip after the query selector. Do you know anyone may know? @JackHowa

**Comment by JackHowa** [comment]
@amyerz I believe Brent worked on the lightbox more. I'd recommend reaching out to him for testing on it. I'm not sure

**Review by brentmiller1973 — APPROVED** [review]
I don't see how to get a working storybook test for this...So I am approving on the condition that we have a ticket to figure out how to add this test (loading an image into the lightbox in the storybook mdx file) for later on

**Review by beltrancaliz — APPROVED** [review]

**Pull request merged**
