### PR TITLE
change icon svg and add viewBox to camera icon 

### PR DESCRIPTION
**Pull request by kascote**
working on [PEN-814](https://arcpublishing.atlassian.net/browse/PEN-814) After a lot of back and forth and consulting with Brandon I decided change the icon because was impossible to resize it.
The visual aspect is the same as before.

## After
no visual changes

### CODE REVIEW

**Review by jgrosspietsch — APPROVED** [review]
:cool:

**Comment by JackHowa** [comment]
was it intentional to change the size of the arrow icons? https://www.chromatic.com/snapshot?appId=5eed0506faad4f0022fedf95&id=5f579c33f84d490022652771

**Review by JackHowa — CHANGES_REQUESTED** [review]
Can we have @brandonhunty or product stakeholder confirm that the chromatic changes are what we want? see chromatic checks in the in the comment https://www.chromatic.com/build?appId=5eed0506faad4f0022fedf95&number=62

**Comment by JackHowa** [comment]
Screen Shot 2020-09-09 at 12 28 31 PM
You should already be able to do this @kascote . Look at the storybook examples under icon.

**Comment by kascote** [comment]
@JackHowa I think that build #62 on chromatic make reference to the other pull request no to this one. I think this one is this https://www.chromatic.com/build?appId=5eed0506faad4f0022fedf95&number=61

The other pull request https://github.com/WPMedia/engine-theme-sdk/pull/88, yes I updated the story book and all the icons to see which ones can be resized without relay on adhoc css. And that can generate the changes you are seeing on chromatic.

**Comment by JackHowa** [comment]
Please look at https://staging.arcpublishing.com/alc/docs/storybooks/engine-theme-sdk/?path=/docs/icon--custom-height-and-width for how to resize images. the svgs can be resized with height and width

**Review by JackHowa — APPROVED** [review]
Updated the storybook and the icon path and viewbox so that the icon is resizable. This was a blocker for a blocks pr

**Comment by JackHowa** [comment]
will merge and publish to canary. that way your nested dependencies should get this fix @kascote as well rather than linking

**Pull request merged**
