### PR TITLE
TMEDIA-227: Ensure first level of accessible contrast level

### PR DESCRIPTION
**Pull request by JackHowa**
blocks-related test instructions ... https://github.com/WPMedia/fusion-news-theme-blocks/pull/901

ac: Update relevant text color to be #6c7778 so it passes this color contrast audit

# Test Instructions
- `npm run storybook` 
- look at custom gallery and accessibility warnings. should be none now 
- using rec'd color #6c7778 via https://arcpublishing.atlassian.net/secure/RapidBoard.jspa?rapidView=875&modal=detail&selectedIssue=TMEDIA-227

before 

Screen Shot 2021-04-30 at 15 23 39

after 

Screen Shot 2021-06-10 at 09 34 04

related to #209 for metadata on images

### CODE REVIEW

**Comment by JackHowa** [comment]
Not sure if I like the arc grey (kinda purplish) here https://5eed0506faad4f0022fedf95-pftqjntabv.chromatic.com/?path=/story/gallery--custom-gallery or the original proposed one via dev tools based on contrast here https://5eed0506faad4f0022fedf95-ivcueqricd.chromatic.com/?path=/story/gallery--custom-gallery (kind of looks more natural and black)

**Comment by JackHowa** [comment]
Screen Shot 2021-04-30 at 15 52 30

looks like the actual mock proposed value doesn't meet criteria either 

Screen Shot 2021-04-30 at 15 51 06
https://app.zeplin.io/project/5ea04773df4e1b7ae81167f8/screen/5eb02f6aac15301a694d942d

**Comment by JackHowa** [comment]
tracked https://arcpublishing.atlassian.net/browse/TMEDIA-227

**Review by farleyawapo — APPROVED** [review]
🚀

**Pull request merged**
