### PR TITLE
PEN-435 implemented interstitial Ads

### PR DESCRIPTION
**Pull request by kascote**
## Description
implemented interstitial Ads

## Jira Ticket
- [PEN-435](https://arcpublishing.atlassian.net/browse/PEN-435)

## Acceptance Criteria
- A new Theme Setting is introduced called Gallery cube clicks 
- If this Theme setting is present for a website and is set to a number, this number should be used for how many clicks there are between interstitial ads – 
  - e.g. if Gallery cube clicks is set to 7, then every 7 clicks (either forwards or backwards in the gallery), the gallery cube ad (specifications above) should appear
  - The ad should appear in both inline gallery view and lightbox gallery view, across all breakpoints
  - This applies to wherever the gallery appears – as a standalone Gallery Block, or when a gallery is in the Lead Art or Article Body Block 
  - Per the designs, the ad should be centered within the available picture viewing space; a black background should be applied.
  - Note: The Skip Ad button shown in designs is not needed in this ticket 
  - If this Theme Setting is not present, then no gallery cube ad should appear within the gallery

**Note**: The lightbox component does not support mixed content. We can't add the Ad between the images.

## Test Steps
- Add a gallery block to a page
- setup the content source to `content-api`
- setup the website url to `/gallery/2019/12/12/winter-snow-scenes-gallery/`
- using the site `the-sung` every 3 clicks must show an ad
- using the site `dagen` every 3 clicks must show and ad
- to test the the gallery on the lead art component can use this story as global content `/news/2020/11/04/story-that-has-a-gallery-without-a-basic-promo-image-as-lead-art/`

### Before
is new feature

### After
Screen Recording 2020-11-16-19 56 31

## Dependencies or Side Effects
- FP blocks.json must include the following property: `galleryCubeClicks` specifying the # of clicks between ads.
- PR from `fusion-news-theme-block` https://github.com/WPMedia/fusion-news-theme-blocks/pull/560

## Review Checklist
- [x] Confirmed all the test steps above are working
- [x] Confirmed there are no linter errors
- [x] Confirmed this PR has reasonable code coverage
  - x ] Confirmed this PR has unit test files
  - [x] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [x] Confirmed relevant documentation has been updated/added.

### CODE REVIEW

**Comment by beltrancaliz** [comment]
@kascote is this merged into the `PEN-435-gallery-insterstitial-cube` correctly? It looks like you're trying to push a bunch of unrelated files to the canary branch, a lot of them seem to already be there

**Comment by kascote** [comment]
@beltrancaliz I don't remember to saw all that commits when I generated the PR, could be they generated but the *force-pushed* ?

**Comment by beltrancaliz** [comment]
@kascote Jack made a fix with your changes, can you verify this has all of your work? https://github.com/WPMedia/engine-theme-sdk/pull/130/files

**Comment by kascote** [comment]
@beltrancaliz yes seems to be all there. I downloaded the code and tested visually too, and works ok

**Pull request merged**
